# Generated by Django 3.2 on 2024-01-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
