# Generated by Django 3.2 on 2024-01-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0002_alter_prestamo_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='nacionalidad',
            field=models.CharField(max_length=20),
        ),
    ]
