# Generated by Django 3.2 on 2024-01-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0003_alter_lector_nacionalidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name': 'Lector', 'verbose_name_plural': 'Lectores'},
        ),
        migrations.AlterField(
            model_name='lector',
            name='nacionalidad',
            field=models.CharField(max_length=30),
        ),
    ]
